# Generated by Django 3.1.2 on 2020-10-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0002_auto_20201008_1545'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tweet',
            table='tweets',
        ),
    ]
